export const ADD_TO_CART = "ADD_TO_CART";
export const SET_PRODUCT = "SET_PRODUCT";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const ADD_SPONSOR_CODE = "ADD_SPONSOR_CODE";
